name: CI
on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        pg: [12]
    name: ğŸ˜ PostgreSQL ${{ matrix.pg }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Download and start PostgreSQL
        run: sudo ./ci/ubuntu-install.sh ${{ matrix.pg }}
      - name: Install libraries
        run: sudo apt-get -y install zlib1g-dev
      - name: Build and test
        run: make && make install && make installcheck
